import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

const questions = [
  { key: 'name', question: 'What should we call you?', hint: 'Your name', type: 'text' },
  { key: 'project', question: 'What are you building?', hint: 'Company, product, or project', type: 'text' },
  { key: 'message', question: 'What problem are you ready to solve?', hint: 'Share the opportunity, challenge, or ambition', type: 'textarea' },
  { key: 'timeline', question: 'When would you like to launch?', hint: 'e.g. 3–6 months', type: 'text' },
  { key: 'budget', question: 'What investment range feels right?', hint: 'e.g. $25k–$50k', type: 'text' },
  { key: 'email', question: 'Where can we continue the conversation?', hint: 'you@company.com', type: 'email' },
];

export default function Contact() {
  const [answers, setAnswers] = useState({}); const [step, setStep] = useState(0); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  const item = questions[step]; const value = answers[item?.key] || '';
  const advance = (event) => { event.preventDefault(); if (!value.trim()) return; setStep((current) => Math.min(current + 1, questions.length)); };
  const send = async () => { setSending(true); await new Promise((resolve) => setTimeout(resolve, 1300)); setSending(false); setSent(true); };
  return <section id="contact" className="conversation-center relative min-h-[920px] overflow-hidden py-24"><div className="conversation-aurora" /><div className="conversation-particles" /><div className="conversation-shell relative z-10 max-w-5xl mx-auto px-6"><header className="conversation-heading"><span>NEURALL / COMMUNICATION CENTER</span><h2>Let’s make your next idea <em>real.</em></h2></header><div className={`conversation-orb ${sending ? 'conversation-orb--sending' : ''} ${sent ? 'conversation-orb--sent' : ''}`}><i /><i /><i /><b>AI</b></div><main className="conversation-window"><AnimatePresence mode="wait">{sent ? <motion.div key="sent" initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} className="conversation-success"><span>TRANSMISSION COMPLETE</span><h3>Your idea has been received.</h3><p>We’ll reach out soon. Let’s build the future together.</p><button type="button" onClick={() => { setSent(false); setStep(0); setAnswers({}); }}>Begin another conversation</button></motion.div> : step === questions.length ? <motion.div key="summary" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="conversation-summary"><span>HERE’S WHAT I UNDERSTOOD</span><h3>{answers.name}, we’re ready to explore {answers.project}.</h3><div>{[['PROJECT', answers.project], ['TIMELINE', answers.timeline], ['SCOPE', answers.budget], ['CONTACT', answers.email]].map(([label, detail]) => <p key={label}><i>{label}</i><b>{detail}</b></p>)}</div><button type="button" onClick={send} disabled={sending}>{sending ? 'Transmitting intelligence…' : 'Send this to Neurall ↗'}</button></motion.div> : <motion.form key={item.key} onSubmit={advance} initial={{ opacity: 0, filter: 'blur(9px)', y: 15 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} exit={{ opacity: 0, y: -12 }} className="conversation-question"><div className="conversation-ai"><i>NEURALL</i><span>{step === 0 ? 'Hello. I’m Neurall. I’d love to learn about your next idea.' : 'I’m listening.'}</span></div><label htmlFor={item.key}>{item.question}</label>{item.type === 'textarea' ? <textarea autoFocus id={item.key} value={value} onChange={(event) => setAnswers({ ...answers, [item.key]: event.target.value })} placeholder={item.hint} rows="4" /> : <input autoFocus id={item.key} type={item.type} value={value} onChange={(event) => setAnswers({ ...answers, [item.key]: event.target.value })} placeholder={item.hint} /> }<div className="conversation-actions"><span>{String(step + 1).padStart(2, '0')} / 06</span><button type="submit">Continue <b>↗</b></button></div></motion.form>}</AnimatePresence></main></div></section>;
}
