import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

const team = [
  { name: 'Alex Morgan', role: 'CEO & AI Lead', initials: 'AM', accent: '#00e5ff', experience: '12 years / intelligence systems', skills: ['AI Strategy', 'LLM Systems', 'Research'], project: 'Nexus Intelligence' },
  { name: 'Sophia Reeves', role: 'Design Director', initials: 'SR', accent: '#c177ff', experience: '10 years / human interfaces', skills: ['Design Systems', 'Product UX', 'Motion'], project: 'Aether Commerce' },
  { name: 'Daniel Kim', role: 'Lead Engineer', initials: 'DK', accent: '#54e2a4', experience: '11 years / platform engineering', skills: ['React', 'Cloud', 'Architecture'], project: 'FlowMind OS' },
  { name: 'Layla Hassan', role: 'ML Architect', initials: 'LH', accent: '#ffad5b', experience: '9 years / applied machine learning', skills: ['Neural Nets', 'Vision', 'Automation'], project: 'Pulse Health' },
];

function SkillConstellation({ member }) { return <div className="skill-constellation">{member.skills.map((skill, index) => <button type="button" title={skill} key={skill} style={{ '--skill-index': index, '--pod-accent': member.accent }}><i /><span>{skill}</span></button>)}<svg viewBox="0 0 200 90" aria-hidden="true"><path d="M20 55 92 18 175 48M20 55 92 70 175 48" /></svg></div>; }
function Pod({ member, active, onSelect, index }) { return <motion.button type="button" aria-pressed={active} onClick={onSelect} style={{ '--pod-accent': member.accent }} className={`research-pod ${active ? 'research-pod--active' : ''}`} initial={{ opacity: 0, scale: .65 }} whileInView={{ opacity: 1, scale: 1 }} transition={{ delay: index * .12, type: 'spring', stiffness: 100, damping: 15 }} whileHover={{ y: -10 }}><span className="research-pod__scan" /><span className="research-pod__halo" /><span className="research-pod__avatar">{member.initials}</span><strong>{member.name}</strong><small>{member.role}</small><i className="research-pod__id">RESEARCHER_{String(index + 1).padStart(2, '0')}</i></motion.button>; }

export default function Team() {
  const [active, setActive] = useState(0); const member = team[active];
  return <section id="team" className="research-lab relative min-h-[970px] overflow-hidden bg-black py-24"><div className="research-lab__grid" /><div className="research-lab__light" style={{ '--pod-accent': member.accent }} /><header className="research-lab__header relative z-10 max-w-7xl mx-auto px-6 lg:px-8"><span>NEURALL / RESEARCH CENTER</span><h2>Meet the minds <em>building next.</em></h2><p>A multidisciplinary research collective, connected by a shared intelligence core.</p></header><div className="research-room relative mx-auto max-w-6xl px-6"><svg className="research-links" viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><path d="M500 255 195 140M500 255 805 140M500 255 195 390M500 255 805 390" /></svg><div className="research-core"><b>AI</b><span>COLLABORATION<br />CORE</span></div>{team.map((item, index) => <Pod key={item.name} member={item} index={index} active={index === active} onSelect={() => setActive(index)} />)}<AnimatePresence mode="wait"><motion.article key={member.name} initial={{ opacity: 0, filter: 'blur(10px)', y: 14 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} exit={{ opacity: 0, y: -10 }} className="research-profile" style={{ '--pod-accent': member.accent }}><div className="research-profile__bar"><span>IDENTITY // VERIFIED</span><i /></div><h3>{member.name}</h3><strong>{member.role}</strong><p>{member.experience}</p><div><span>ACTIVE RESEARCH</span><b>{member.project}</b></div><SkillConstellation member={member} /></motion.article></AnimatePresence></div><div className="research-lab__footer">SELECT A POD TO OPEN RESEARCH PROFILE <i>◌</i></div></section>;
}
