import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

const testimonials = [
  { name: 'Sarah Chen', role: 'CTO, Vanta Systems', avatar: 'SC', location: 'San Francisco', impact: '80%', metric: 'faster data processing', text: 'Neurall completely transformed our data pipeline. The AI models they built reduced our processing time by 80% and the quality was unmatched.', accent: '#00e5ff' },
  { name: 'Marcus Rodriguez', role: 'CEO, Apex Digital', avatar: 'MR', location: 'Madrid', impact: '3.4×', metric: 'delivery velocity', text: 'They didn’t just build what we asked — they challenged our thinking and delivered something far better.', accent: '#a970ff' },
  { name: 'Priya Sharma', role: 'Product Lead, Luminary', avatar: 'PS', location: 'Bengaluru', impact: '45%', metric: 'conversion increase', text: 'The UI they created was absolutely stunning. Our conversion rate jumped 45% after launch.', accent: '#50dfa9' },
  { name: 'James Whitfield', role: 'Founder, NovaTech', avatar: 'JW', location: 'London', impact: '10 wk', metric: 'idea to launch', text: 'The team’s ability to move fast without sacrificing quality is genuinely rare in this industry.', accent: '#ffad5b' },
  { name: 'Ava Lindström', role: 'Head of Design, Bloom', avatar: 'AL', location: 'Stockholm', impact: '96', metric: 'experience score', text: 'The attention to micro-interactions and animation quality set our app apart from every competitor.', accent: '#ff79bf' },
  { name: 'Kevin Park', role: 'VP Engineering, DataFlow', avatar: 'KP', location: 'Seoul', impact: '$200K', metric: 'annual savings', text: 'Their cloud architecture expertise saved us $200K in annual infrastructure costs.', accent: '#5b9dff' },
];

function TrustNode({ client, index, active, onSelect }) { return <button type="button" onClick={() => onSelect(index)} aria-pressed={active} style={{ '--trust-accent': client.accent, '--node-x': `${[21, 65, 75, 38, 55, 84][index]}%`, '--node-y': `${[30, 23, 55, 66, 38, 72][index]}%` }} className={`trust-node ${active ? 'trust-node--active' : ''}`}><i /><span>{client.location}</span></button>; }
function Transmission({ client }) { return <motion.article key={client.name} initial={{ opacity: 0, filter: 'blur(10px)', y: 18 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} exit={{ opacity: 0, y: -10 }} className="trust-transmission" style={{ '--trust-accent': client.accent }}><div className="trust-transmission__bar"><span>INCOMING TRANSMISSION // {client.location.toUpperCase()}</span><i /></div><div className="trust-client"><b>{client.avatar}</b><div><strong>{client.name}</strong><span>{client.role}</span></div><em>★★★★★</em></div><p>“{client.text}”</p><div className="trust-impact"><strong>{client.impact}</strong><span>{client.metric}</span><i /><i /><i /><i /><i /></div></motion.article>; }

export default function Testimonials() { const [active, setActive] = useState(0); const client = testimonials[active]; return <section id="testimonials" className="trust-network relative min-h-[980px] overflow-hidden bg-black py-24"><div className="trust-stars" /><header className="trust-header relative z-10 max-w-7xl mx-auto px-6 lg:px-8"><span>NEURALL / GLOBAL TRUST NETWORK</span><h2>Built with teams <em>everywhere.</em></h2><p>Worldwide systems. Long-term partnerships. Measurable change.</p></header><div className="trust-world relative mx-auto max-w-6xl px-6"><div className="trust-globe"><span className="trust-globe__grid" /><span className="trust-globe__orbit" /><i>GLOBAL<br />NETWORK</i></div><svg className="trust-routes" viewBox="0 0 1000 570" preserveAspectRatio="none" aria-hidden="true"><path d="M500 275Q320 100 210 170M500 275Q650 90 650 130M500 275Q780 210 750 310M500 275Q390 400 380 380M500 275Q560 340 550 220M500 275Q720 420 840 410" /></svg>{testimonials.map((item, index) => <TrustNode key={item.name} client={item} index={index} active={index === active} onSelect={setActive} />)}<AnimatePresence mode="wait"><Transmission client={client} /></AnimatePresence></div><div className="trust-proof"><span><b>100+</b> PROJECTS DELIVERED</span><span><b>98%</b> CLIENT SATISFACTION</span><span><b>24/7</b> GLOBAL SUPPORT</span></div></section>; }
